// app/src/pages/Login.jsx
import Button from '@/components/ui/button/Button.jsx';
import Input from '@/components/ui/input/Input.jsx';
import cn from 'clsx';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card/Card.jsx';
import { useNavigate } from 'react-router-dom';

export default function Login() {
  const navigate = useNavigate();
  return (
    <div className="flex w-full items-center justify-center p-6 md:p-10">
      <div className="w-full max-w-sm">
        <div className={ cn("flex flex-col gap-6") }>
          <Card>
            <CardHeader>
              <CardTitle className="text-2xl">Login</CardTitle>
            </CardHeader>
            <CardContent>
              <form>
                <div className="flex flex-col gap-6">
                  <div className="grid gap-2">
                    <label htmlFor="email">Email</label>
                    <Input
                      id="email"
                      type="email"
                      placeholder="abc@example.com"
                      required
                    />
                  </div>
                  <Button type="submit" className="w-full" label="Send OTP" />
                </div>
                <div className="mt-4 text-center text-sm">
                  Don&apos;t have an account?{" "}
                  <span onClick={ () => navigate('/signup') } className="underline underline-offset-4">
                    Sign up
                  </span>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

// ui/src/app/features/auth/pages/login/login.component.ts
import { Component } from '@angular/core';
import { AuthApiService } from '../../auth-api.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

enum LoginState {
  INITIATED,
  EMAIL_INVALID ,
  OTP_REQUESTED,
  INVALID_OTP,
  SUCCESS
}

@Component({
  selector: 'app-login',
  imports: [
    FormsModule,
    CommonModule
  ],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {
  state: LoginState = LoginState.INITIATED;
  email = '';
  rememberMe = false;
  otp = '';

  constructor(
    private authApiService: AuthApiService,
    private router: Router
  ) {}

  async submitLogin() {
    try {
      await this.authApiService.verifyLoginOTP(
        this.email,
        this.otp,
        this.rememberMe
      )
      this.state = LoginState.SUCCESS;
      await this.router.navigate(['/'])
    } catch(err) {
      this.state = LoginState.INVALID_OTP;
    }
  }

  async submitOTP() {
    try {
      await this.authApiService.requestLoginOTP(this.email);
      this.state = LoginState.OTP_REQUESTED;
    } catch(err) {
      this.state = LoginState.EMAIL_INVALID;
    }
  }

  gotoSignup() {
    this.router.navigate(['/signup']);
  }

  protected readonly LoginStage = LoginState;
  protected readonly LoginState = LoginState;
}

<div class="card max-w-sm mx-auto mt-16">
  <div class="card__header">
    <div class="card__header__title">Login</div>
  </div>
  <div class="card__body">
    <div class="flex flex-col justify-center">
      @if (state >= LoginStage.OTP_REQUESTED) {
        <div class="input-group">
          <label class="input-group__label">Email</label>
          <input type="email" class="input-group__input" [value]="email" disabled>
        </div>
        <div class="input-group">
          <label class="input-group__label">OTP</label>
          <input type="text" class="input-group__input" [class]="state === LoginState.INVALID_OTP && 'danger'" [(ngModel)]="otp">
          @if (state === LoginState.INVALID_OTP) {
            <span class="input-group__error">Invalid OTP</span>
          }
        </div>
        <div class="input-group input-group--inline">
          <input type="checkbox" [(ngModel)]="rememberMe"> Remember me
        </div>
        <button (click)="submitLogin()" class="btn btn--primary">Verify Login</button>
      } @else {
        <div class="input-group">
          <label class="input-group__label">Email</label>
          <input type="text" class="input-group__input" [class]="state === LoginState.EMAIL_INVALID && 'danger'" placeholder="john.doe@email.com" [(ngModel)]="email">
          @if (state === LoginState.EMAIL_INVALID) {
            <span class="input-group__error">Invalid email</span>
          }
        </div>
        <button (click)="submitOTP()" class="btn btn--primary">Send OTP</button>
        <div class="mt-4 text-center text-sm">
          Don&apos;t have an account?{{" "}}
          <a (click)="gotoSignup()" class="underline underline-offset-4">
            Sign up
          </a>
        </div>
      }
    </div>
  </div>
</div>
